create database testlogback;

CREATE TABLE `tb_user_log` (
  `ID` VARCHAR(40) NOT NULL COMMENT '主键',
  `ACCOUNT` VARCHAR(20) DEFAULT NULL COMMENT '账号',
  `USER_ID` VARCHAR(20) NOT NULL COMMENT '用户主键(身份证号或者唯一id)',
  `USER_NAME` VARCHAR(20) DEFAULT NULL COMMENT '用户名称',
  `ORG_CODE` VARCHAR(30) DEFAULT NULL COMMENT '组织机构编码',
  `ORG_NAME` VARCHAR(30) DEFAULT NULL COMMENT '组织机构编码',
  `IP` VARCHAR(30) DEFAULT NULL COMMENT '操作主机IP',
  `DESCRIPTION` VARCHAR(5000) DEFAULT NULL COMMENT '操作描述',
  `LEVER` INT(11) DEFAULT NULL COMMENT '操作等级 1 成功 0 失败',
  `CREATE_TIME` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;